name: FTP Deploy

on: push

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: hosted10.nfoservers.com
        FTP_USERNAME: shiden
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        REMOTE_DIR: /usr/www/shiden/public/Gifter
        METHOD: sftp
        ARGS: --delete
        # --delete arg will delete files on the server if you've deleted them in git
